language: rust

os:
  - linux

cache: cargo

addons:
  apt:
    sources:
      - sourceline: 'ppa:wireguard/wireguard'
    packages:
      - linux-headers-$(uname -r)
      - wireguard

before_install:
  - sudo ip link add wgtest0 type wireguard
  - sudo ip link add wgtest12 type wireguard

script:
  - cargo build --verbose
  - cargo build --tests --verbose
  # Give compiled tests the ability to set and read WireGuard devices. Otherwise
  # they will likely fail with access/permission errors.
  - find ./target/debug -maxdepth 1 -type f -executable | xargs -n 1 sudo setcap CAP_NET_ADMIN=+eip
  - cargo test --verbose
