[package]
name = "wireguard-uapi"
version = "0.1.0"
edition = "2018"
authors = ["Brandon Cheng <brandon.cheng@protonmail.com>"]
license = "MIT"
repository = "https://github.com/gluxon/wireguard-uapi-rs"

[dependencies]
buffering = { version = "0.3.2",  features = ["copy"] }
derive_builder = "0.7.1"
failure = "0.1.5"
libc = "0.2.51"
neli = "0.4.3-r2"

[dev-dependencies]
base64 = "0.10.1"
colored = "1.7"
predicates = "1"
rand = "0.6.5"
